### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by robbedoeske** [cline-pk/Multics-auto-exchange-php7.2-all-multics-version-supported#1]
When creating C line or N line it always display offline?
Cache also not working, nothing added to Cache.cfg (editor1)

**Comment by cline-pk** [comment]
Have your correctly setup your editor IDs ?
can you send multics editor option screenshot and script config screenshot .

**Comment by robbedoeske** [comment]
I think you mean this?

![image](https://user-images.githubusercontent.com/60922597/165330283-09ed41ed-0114-481d-86bd-fc3d3a7b10a3.png)

And this
![Schermafbeelding 2022-04-26 om 17 06 42](https://user-images.githubusercontent.com/60922597/165331976-d188e75d-5f38-4810-a5df-0929751cdd0c.png)

**Comment by cline-pk** [comment]
It's seems everything is ok.
Can you share your exchange link to check it live.

**Comment by robbedoeske** [comment]
http://itsalways.better-than.tv/index.php

**Comment by robbedoeske** [comment]
So there is no solution? I really like this script.

**Comment by cline-pk** [comment]
well i think the currently multics version are you using not compatible with this script due to to many changes in multics 
can you share here the bin file so i'll install in on my server and try to make next release of this script to support possible version of multics in that script.

**Comment by robbedoeske** [comment]
Oke will try older version, the version i now have is this one:
[r84-S.x64.zip](https://github.com/cline-pk/Multics-auto-exchange-php7.2-all-multics-version-supported/files/8572467/r84-S.x64.zip)

**Comment by cline-pk** [comment]
okay i'll check and update script.

**Comment by robbedoeske** [comment]
Hmmm i tried many different versions from r81 to r84 and different configs but nothing works?
Can you share link where it works?
